version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_DATABASE=postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  postgres_data:
    driver: local
